### ISSUE TITLE
Failed to execute warp transaction

### ISSUE THREAD

**Issue by idoroshenko** [warp-id/solana-trading-bot#164]
Hi,

I get this error for every warp executor transaction attempt. The response is always empty. I logged the entire error to investigate:

error: {
      "message": ": ",
      "name": "AggregateError",
      "stack":
          AggregateError
              at Function.AxiosError.from (C:\Users\idoroshenko\projects\solana-trading-bot\node_modules\axios\lib\core\AxiosError.js:89:14)
              at RedirectableRequest.handleRequestError (C:\Users\idoroshenko\projects\solana-trading-bot\node_modules\axios\lib\adapters\http.js:610:25)
              at RedirectableRequest.emit (node:events:531:35)
              at ClientRequest.eventHandlers.<computed> (C:\Users\idoroshenko\projects\solana-trading-bot\node_modules\follow-redirects\index.js:38:24)
              at ClientRequest.emit (node:events:519:28)
              at ClientRequest.emit (node:domain:488:12)
              at TLSSocket.socketErrorListener (node:_http_client:492:9)
              at TLSSocket.emit (node:events:519:28)
              at TLSSocket.emit (node:domain:488:12)
              at Axios.request (C:\Users\idoroshenko\projects\solana-trading-bot\node_modules\axios\lib\core\Axios.js:45:41)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
          caused by: AggregateError
              at internalConnectMultiple (node:net:1116:18)
              at afterConnectMultiple (node:net:1680:7)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 100000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/json",
          "User-Agent": "axios/1.6.8",
          "Content-Length": "1513",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "method": "post",
        "url": "https://tx.warp.id/transaction/execute",
        "data": "{\"transactions\":[\"removed transaction data"],\"latestBlockhash\":{\"blockhash\":\"4TFJ8naCHUw5hErZG3hsy9SpX1uH22WFRsxuUdFAqCmq\",\"lastValidBlockHeight\":279268981}}"
      },
      "code": "EACCES",
      "status": null
    }

**Comment by Omnivers** [comment]
Привіт, змініть .env на Jito замість Default
`TRANSACTION_EXECUTOR=jito`
